name: node-cicd

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'App'

    - name: Build Docker Image
      run: |
        ls -l
      working-directory: App

  # unit-test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Push Image DockerHub
  #     run: |
  #       docker run -d -p 3000:8080 --name hello-world --rm adhocam/hello-world
  #       curl -s localhost:3000