name: node-cicd

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'App'

    - name: Build Image
      run: |
        docker build -t hello-world .
        docker images
      working-directory: App

    - name: Test
      run: |
        docker stop hello-world
        docker run -d -p 3000:8080 --name hello-world --rm hello-world
        docker ps
        $resp=$(curl -s localhost:3000)

        if [[ $resp == "Hello World!" ]]; then
          docker stop hello-world
          echo "Application works fine" && exit 0
        else
          echo "Something went wrong. See the response bellow for the hint..."
          curl -i localhost:3000
          docker stop hello-world
          exit 1
      working-directory: App

  # push:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Push Image DockerHub
  #     env:
  #           DockerHub_User: ${{ github.Dockerhub_User }}
  #           DockerHub_PAT: ${{ secrets.DockerHub_PAT  }}
  #     run: |
  #       docker login -u $DockerHub_User -p $DockerHub_PAT
  #       docker image tag hello-world:latest adhocam/hello-world:latest
  #       docker image push adhocam/hello-world:latest