name: node-cicd

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: 'App'
    - name: Build Docker Image
      run: |
        cd App
        docker build -t hello-world .
        docker images
        docker run -d -p 3000:8080 --name hello-world --rm hello-world
        docker ps
 
        curl -s localhost:3000

  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Push Image DockerHub
      run: |
        docker run -d -p 3000:8080 --name hello-world --rm adhocam/hello-world
        resp=$(curl -s localhost:3000)
        
        echo $resp