name: node-cicd

on: workflow_dispatch

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'App'
    
    - name: Set Node version
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1'

    - name: Unit Tests
      run: |
        npm install
        npm test -- test/hello-world.test.js
      working-directory: App

  # build-push:
  #   needs: unit-test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       sparse-checkout: 'App'

  #   - name: Build Push Image
  #     env:
  #       DockerHub_User: ${{ github.Dockerhub_User }}
  #       DockerHub_PAT: ${{ secrets.DockerHub_PAT  }}
  #     run: |
  #       echo "Build Image"
  #       docker build -t hello-world .
  #       docker images
        
  #       echo "Tag image for DockerHub"
  #       docker login -u $DockerHub_User -p $DockerHub_PAT
  #       docker image tag hello-world:latest ${{ github.Dockerhub_User }}/hello-world:latest
  #       docker image push ${{ github.Dockerhub_User }}/hello-world:latest
        
  #       echo "Checked DockerHub image pushed"
  #       docker search ${{ github.Dockerhub_User }}/hello-world
  #     working-directory: App